### ISSUE TITLE
May I ask a question about demod？

### ISSUE THREAD

**Issue by zhaohengbo** [srsampson/mFSK#1]
Thanks for your contribution .
I have trouble in understanding some code,expecially the method of "Fine Timing Estimation" in demodulation.c.
Could you please give a concise explain?
Thank you.

**Comment by srsampson** [comment]
This code comes from David Rowe from his program, so I'm not quite up to speed on how it works. He does do some analysis in Octave, so this was probably just empirically designed. Thus the term "magic".

I do not have a concise explanation, so email David at david@rowetel.com

**Comment by zhaohengbo** [comment]
Thank you , I'm trying to observe the intermediate data of the process, maybe I could find something.

**Comment by zhaohengbo** [comment]
After a few tests, it is clear that this is single point DFT. As the base-band data is mod by certain frequency, we can get a coarse phase offset at that frequency.
